version: '3'

services:
  whoami1:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    networks:
      - traefik2-test_traefik
    labels:
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=PathPrefix(`/findme`)"
      - "traefik.http.routers.web.middlewares=add-foo"
      - "traefik.http.middlewares.add-foo.addprefix.prefix=/foo"
      - "traefik.http.services.web.loadBalancer.healthCheck.path=/"

  whoami2:
    image: emilevauge/whoami # A container that exposes an API to show its IP address
    networks:
      - traefik2-test_traefik
    labels:
      - "traefik.http.routers.web.entrypoints=http"
      - "traefik.http.routers.web.rule=PathPrefix(`/findme`)"
      - "traefik.http.routers.web.middlewares=add-foo"
      - "traefik.http.middlewares.add-foo.addprefix.prefix=/foo"
      - "traefik.http.services.web.loadBalancer.healthCheck.path=/"

networks:
  traefik2-test_traefik:
    external: true
