version: '3'

services:
  echo:
    image: hashicorp/http-echo
    command: "--text hello"
    networks:
      - traefik2-test_traefik
    labels:
      - "traefik.http.routers.web-secure.entrypoints=https"
      - "traefik.http.routers.web-secure.tls=true"
      - "traefik.http.routers.web-secure.rule=Host(`echo.testing.com`) && Path(`/standard`)"

networks:
  traefik2-test_traefik:
    external: true
